# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, upload_to='media/covers/categories/%Y/%m/%d/', verbose_name='cover'),
        ),
    ]
