# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-31 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180129_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'published'), (2, 'draft'), (3, 'hidden'), (4, 'secret')], default=2, verbose_name='status'),
        ),
    ]
