# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180201_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/categories/', verbose_name='封面(教程使用)'),
        ),
        migrations.AlterField(
            model_name='img',
            name='head_pic',
            field=models.ImageField(upload_to='blog/%Y%m%d/', verbose_name='图片'),
        ),
    ]
